// src/dialogs/about_lic.tsx
/* Web Lic - Copyright (C) 2018 Remi Gagne */

import React from "react";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogTitle from "@mui/material/DialogTitle";

import { Button } from "../components/button";

import packageInfo from "../../package.json";
import { tr } from "../translations";

interface Props {
	onClose: () => void;
}

export default function AboutLicDialog({ onClose }: Props) {
	const version = packageInfo.version;

	return (
		<Dialog
			open
			id="about_lic_dialog"
			onClose={onClose}
			maxWidth={false}
			className="aboutLicDialog"
			PaperProps={{ style: { width: "700px" } }}
		>
			<DialogTitle>{tr("dialog.about_lic.title")}</DialogTitle>
			<DialogContent>
				<h4>{tr("dialog.about_lic.version_@mf", { version })}</h4>
				<div
					dangerouslySetInnerHTML={{
						__html: tr(
							"dialog.about_lic.free_@link",
							"https://github.com/remig/web_lic"
						),
					}}
				/>
				<div
					dangerouslySetInnerHTML={{
						__html: tr(
							"dialog.about_lic.read_more_@link",
							"http://bugeyedmonkeys.com/lic/about/"
						),
					}}
				/>
				<div
					dangerouslySetInnerHTML={{
						__html: tr(
							"dialog.about_lic.ldraw_@link",
							"https://www.ldraw.org/"
						),
					}}
				/>
				<div
					dangerouslySetInnerHTML={{
						__html: tr(
							"dialog.about_lic.contact_@link",
							"https://github.com/remig/web_lic/issues"
						),
					}}
				/>
				<div
					dangerouslySetInnerHTML={{
						__html: tr(
							"dialog.about_lic.lang_@link",
							"https://github.com/remig/web_lic/wiki/Translating-Lic"
						),
					}}
				/>
				<div>
					<strong>{tr("dialog.about_lic.thanks")}</strong>
					<ul style={{ paddingLeft: 30 }}>
						<li>
							{tr("dialog.about_lic.feedback") + " "}
							<a
								href="https://www.flickr.com/photos/legohaulic/"
								target="_blank"
								rel="noreferrer"
							>
								Tyler Clites
							</a>
							{" " + tr("dialog.about_lic.and") + " "}
							<a
								href="http://constructibles.net/"
								target="_blank"
								rel="noreferrer"
							>
								Jason Petrasich
							</a>
						</li>
						<li>
							{tr("dialog.about_lic.german") + " "}
							<a
								href="https://github.com/mried"
								target="_blank"
								rel="noreferrer"
							>
								mried
							</a>
						</li>
						<li>{tr("dialog.about_lic.french")}Jean-Philippe Lechêne</li>
					</ul>
				</div>
				<br />
				<div>
					{tr("dialog.about_lic.copyright") + " "}
					<a href="mailto:lic@bugeyedmonkeys.com">Remi Gagne</a>
				</div>
			</DialogContent>
			<DialogActions>
				<Button variant="ok" onClick={onClose} />
			</DialogActions>
		</Dialog>
	);
}

// src/dialogs/about_lic.vue
/* Web Lic - Copyright (C) 2018 Remi Gagne */

<template>
	<LicDialog
		:title="t('dialog.about_lic.title')"
		width="700px"
		class="aboutLicDialog"
	>
		<div>
			<h4>{{t('dialog.about_lic.version_@mf', {version})}}</h4>
			<!--
				TODO: Add server API to fetch the most recent lic version and display it here
				<p><i class="fas fa-check" />&nbsp;You are using the most recent version of Lic.</p>
			-->
			<p v-html="t('dialog.about_lic.free_@link', 'https://github.com/remig/web_lic')" />
			<p v-html="t('dialog.about_lic.read_more_@link', 'http://bugeyedmonkeys.com/lic/about/')" />
			<p v-html="t('dialog.about_lic.ldraw_@link', 'https://www.ldraw.org/')" />
			<p v-html="t('dialog.about_lic.contact_@link', 'https://github.com/remig/web_lic/issues')" />
			<!-- eslint-disable-next-line max-len -->
			<p v-html="t('dialog.about_lic.lang_@link', 'https://github.com/remig/web_lic/wiki/Translating-Lic')" />
			<p>
				<strong>
					{{t('dialog.about_lic.thanks')}}
				</strong>
			</p>
			<ul>
				<li>
					{{t('dialog.about_lic.feedback')}}
					<a href="https://www.flickr.com/photos/legohaulic/" target="_blank">Tyler Clites</a>
					{{t('dialog.about_lic.and')}}
					<a href="http://constructibles.net/" target="_blank">Jason Petrasich</a>
				</li>
				<li>
					{{t('dialog.about_lic.german')}}
					<a href="https://github.com/mried" target="_blank">mried</a>
				</li>
				<li>{{t('dialog.about_lic.french')}}Jean-Philippe Lechêne</li>
			</ul>
			<br>
			<p>
				{{t('dialog.about_lic.copyright')}}
				<a href="mailto:lic@bugeyedmonkeys.com">Remi Gagne</a>
			</p>
		</div>
		<template #footer>
			<LicButton type="ok" @click="emit('ok')" />
		</template>
	</LicDialog>
</template>

<script setup lang="ts">

import LicButton from '@/components/base/LicButton.vue';
import LicDialog from '@/components/base/LicDialog.vue';

import packageInfo from '../../package.json';
import {t} from '../translations';

const emit = defineEmits<{(e: 'ok'): void; (e: 'cancel'): void}>();

const version = packageInfo.version;

</script>

<style>

.aboutLicDialog {
	ul {
		padding-left: 30px;
	}

	p {
		line-height: 25px;
	}
}

</style>
