// src/dialogs/grid_dialog.tsx
/* Web Lic - Copyright (C) 2018 Remi Gagne */

import React, { useEffect, useState } from "react";
import Checkbox from "@mui/material/Checkbox";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogTitle from "@mui/material/DialogTitle";
import FormControlLabel from "@mui/material/FormControlLabel";

import { Button } from "../components/button";

import cache from "../cache";
import EventBus from "../event_bus";
import { tr } from "../translations";
import uiState from "../ui_state";
import undoStack from "../undo_stack";
import _ from "../util";

interface Props {
	_showArg?: any;
	onClose: () => void;
}

export default function GridDialog({ _showArg, onClose }: Props) {
	const [newState, setNewState] = useState<any>(() =>
		_.cloneDeep(uiState.get("grid"))
	);
	const [useAutoColor, setUseAutoColor] = useState(true);
	const [lineColor, setLineColor] = useState("rgb(0, 0, 0)");
	const originalStateRef = React.useRef<any>(null);

	useEffect(() => {
		const grid = uiState.get("grid");
		const color = grid.line.color;
		setUseAutoColor(color === "auto");
		setLineColor(
			color === "auto" ? "rgb(0, 0, 0)" : _.color.toRGB(color).toString()
		);
		const cloned = _.cloneDeep(grid);
		setNewState(cloned);
		originalStateRef.current = grid;
	}, []);

	function update(updatedState?: any) {
		const state = updatedState ?? newState;
		if (useAutoColor) {
			state.line.color = "auto";
		} else {
			state.line.color = lineColor;
		}
		uiState.set("grid", _.cloneDeep(state));
		cache.set("uiState", "gridPath", null);
		EventBus.emit("redraw-ui", undefined);
	}

	function ok() {
		const storeOp = {
			root: cache.get("uiState", "gridPath"),
			op: "replace",
			path: "/",
			value: null,
		};
		const root = uiState.getCurrentState(),
			op = "replace",
			path = "/grid";
		const change = {
			redo: [{ root, op, path, value: _.cloneDeep(newState) }, storeOp],
			undo: [{ root, op, path, value: originalStateRef.current }, storeOp],
		};
		undoStack.commit(change, null, "Style Grid");
		onClose();
	}

	function cancel() {
		uiState.set("grid", originalStateRef.current);
		cache.set("uiState", "gridPath", null);
		EventBus.emit("redraw-ui", undefined);
		onClose();
	}

	function setField(path: string, value: any) {
		const next = _.cloneDeep(newState);
		_.set(next, path, value);
		setNewState(next);
		update(next);
	}

	return (
		<Dialog
			open
			onClose={onClose}
			maxWidth={false}
			className="gridDialog"
			PaperProps={{ style: { width: "500px" } }}
		>
			<DialogTitle>{tr("dialog.grid.title")}</DialogTitle>
			<DialogContent>
				<div
					style={{
						display: "grid",
						gridTemplateColumns: "140px 1fr",
						gap: "8px 0",
						alignItems: "center",
					}}
				>
					<label>{tr("dialog.grid.enabled")}</label>
					<Checkbox
						checked={!!newState?.enabled}
						onChange={(e) => setField("enabled", e.target.checked)}
					/>
					<label>{tr("dialog.grid.spacing")}</label>
					<input
						type="number"
						className="form-control"
						min={1}
						max={10000}
						value={newState?.spacing ?? 0}
						disabled={!newState?.enabled}
						style={{ width: 80 }}
						onChange={(e) => setField("spacing", parseInt(e.target.value, 10))}
					/>
					<label>{tr("dialog.grid.offset")}</label>
					<div style={{ display: "flex", alignItems: "center", gap: 5 }}>
						<span style={{ marginRight: 10 }}>
							{tr("dialog.grid.offset_top")}
						</span>
						<input
							type="number"
							className="form-control"
							min={-1000}
							max={10000}
							value={newState?.offset?.top ?? 0}
							disabled={!newState?.enabled}
							style={{ width: 80 }}
							onChange={(e) =>
								setField("offset.top", parseInt(e.target.value, 10))
							}
						/>
						<span style={{ margin: "0 10px" }}>
							{tr("dialog.grid.offset_left")}
						</span>
						<input
							type="number"
							className="form-control"
							min={-1000}
							max={10000}
							value={newState?.offset?.left ?? 0}
							disabled={!newState?.enabled}
							style={{ width: 80 }}
							onChange={(e) =>
								setField("offset.left", parseInt(e.target.value, 10))
							}
						/>
					</div>
					<label>{tr("dialog.grid.line_style")}</label>
					<div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
						<div style={{ display: "flex", alignItems: "center", gap: 8 }}>
							<label style={{ width: 70 }}>{tr("glossary.color")}</label>
							<FormControlLabel
								control={
									<Checkbox
										checked={useAutoColor}
										disabled={!newState?.enabled}
										onChange={(e) => {
											setUseAutoColor(e.target.checked);
											update();
										}}
									/>
								}
								label={tr("dialog.grid.auto_color")}
								style={{ marginRight: 15 }}
							/>
							<input
								type="color"
								value={lineColor}
								disabled={useAutoColor || !newState?.enabled}
								onChange={(e) => {
									setLineColor(e.target.value);
									setField("line.color", e.target.value);
								}}
							/>
						</div>
						<div style={{ display: "flex", alignItems: "center", gap: 8 }}>
							<label style={{ width: 70 }}>{tr("dialog.grid.width")}</label>
							<input
								type="number"
								className="form-control"
								min={1}
								max={100}
								value={newState?.line?.width ?? 1}
								disabled={!newState?.enabled}
								style={{ width: 80 }}
								onChange={(e) =>
									setField("line.width", parseInt(e.target.value, 10))
								}
							/>
						</div>
					</div>
				</div>
			</DialogContent>
			<DialogActions>
				<Button variant="cancel" onClick={cancel} />
				<Button variant="ok" onClick={ok} />
			</DialogActions>
		</Dialog>
	);
}

// src/dialogs/grid_dialog.vue
/* Web Lic - Copyright (C) 2018 Remi Gagne */

<template>
	<LicDialog
		:title="t('dialog.grid.title')"
		width="500px"
	>
		<div style="--label-width: 120px">
			<div class="label-input-row">
				{{t('dialog.grid.enabled')}}
				<label class="lic-checkbox">
					<input v-model="newState.enabled" type="checkbox" @change="update">
				</label>
			</div>
			<label class="label-input-row">
				{{t('dialog.grid.spacing')}}
				<input
					v-model.number="newState.spacing"
					:disabled="!newState.enabled"
					min="1"
					max="10000"
					type="number"
					class="form-control"
					@input="update"
				>
			</label>
			<div class="label-input-row">
				{{t('dialog.grid.offset')}}
				<div class="flex-row">
					<span class="gridInlineLabel">{{t("dialog.grid.offset_top")}}</span>
					<input
						v-model.number="newState.offset.top"
						:disabled="!newState.enabled"
						min="-1000"
						max="10000"
						type="number"
						class="form-control"
						@input="update"
					>
					<span class="gridInlineLabel2">{{t("dialog.grid.offset_left")}}</span>
					<input
						v-model.number="newState.offset.left"
						:disabled="!newState.enabled"
						min="-1000"
						max="10000"
						type="number"
						class="form-control"
						@input="update"
					>
				</div>
			</div>
			<hr>
			<div class="label-input-row">
				{{t('dialog.grid.line_style')}}
				<div style="--label-width: 70px">
					<div class="label-input-row">
						{{t('glossary.color')}}
						<div class="flex-row" style="min-height: 34px;">
							<label class="lic-checkbox gridAutoChecbox">
								<input
									v-model="useAutoColor"
									type="checkbox"
									:disabled="!newState.enabled"
									@change="update"
								>
								{{t('dialog.grid.auto_color')}}
							</label>
							<LicColorPicker
								v-show="!useAutoColor"
								v-model="lineColor"
								@change="updateColor"
							/>
						</div>
					</div>
					<label class="label-input-row">
						{{t('dialog.grid.width')}}
						<input
							v-model.number="newState.line.width"
							:disabled="!newState.enabled"
							min="1"
							max="100"
							type="number"
							class="form-control"
							@input="update"
						>
					</label>
					<label class="label-input-row">
						{{t('dialog.grid.dash')}}
						<span>(NYI)</span>
					</label>
				</div>
			</div>
		</div>
		<template #footer>
			<LicButton type="cancel" @click="cancel" />
			<LicButton type="ok" @click="ok" />
		</template>
	</LicDialog>
</template>

<script setup lang="ts">

import {t} from '@/translations';
import {ref} from 'vue';

import LicButton from '@/components/base/LicButton.vue';
import LicColorPicker from '@/components/base/LicColorPicker.vue';
import LicDialog from '@/components/base/LicDialog.vue';

import cache from '../cache';
import * as UiOps from '../ui_ops';
import uiState from '../ui_state';
import undoStack from '../undo_stack';
import _ from '../util';

const emit = defineEmits<{(e: 'ok'): void; (e: 'cancel'): void}>();

const grid = uiState.get('grid');
const useAutoColor = ref(grid.line.color === 'auto');
const autoLineColor = 'rgb(0, 0, 0)';
const lineColor = ref(grid.line.color === 'auto' ? autoLineColor : _.color.toRGB(grid.line.color).toString());
const newState = ref(_.cloneDeep(grid));
const originalState = grid;

function update() {
	if (useAutoColor.value) {
		newState.value.line.color = 'auto';
	} else {
		newState.value.line.color = lineColor.value;
	}
	uiState.set('grid', _.cloneDeep(newState.value));
	cache.set('uiState', 'gridPath', null);
	UiOps.drawCurrentPage();
}

function updateColor(newColor: string) {
	newState.value.line.color = lineColor.value = newColor;
	update();
}

function ok() {
	const root = uiState.getCurrentState(), op = 'replace', path = '/grid';
	const redo = [{root, op, path, value: _.cloneDeep(newState.value)}];
	const undo = [{root, op, path, value: originalState}];
	const gridPathCache = cache.get('uiState', 'gridPath');
	if (gridPathCache != null) {
		const storeOp = {root: gridPathCache, op: 'replace', path: '/', value: null};
		redo.push(storeOp);
		undo.push(storeOp);
	}
	undoStack.commit({redo, undo}, null, 'Style Grid');
	emit('ok');
}

function cancel() {
	uiState.set('grid', originalState);
	cache.set('uiState', 'gridPath', null);
	UiOps.drawCurrentPage();
	emit('cancel');
}

</script>

<style>

input[type="number"] {
	width: 80px;
}

.gridInlineLabel {
	margin-right: 10px;
}

.gridInlineLabel2 {
	margin: 0 10px;
}

.gridAutoChecbox {
	margin-right: 15px;
}

</style>
