// src/dialogs/ld_color_picker.tsx
/* Web Lic - Copyright (C) 2018 Remi Gagne */

import React from "react";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogTitle from "@mui/material/DialogTitle";

import { Button } from "../components/button";

import LDParse from "../ld_parse";
import Storage from "../storage";
import { tr } from "../translations";
import _ from "../util";

const customColors = Storage.get.customBrickColors() as any;

function buildColorTable() {
	const colors: { id: number; name: string; color: string; edge: string }[] =
		[];
	_.forOwn(LDParse.colorTable as any, (v: any, k: string) => {
		if (v.color < 0 || v.edge < 0) {
			return;
		}
		const id = parseInt(k, 10);
		const customColor = customColors[id] || {};
		colors.push({
			id,
			name: v.name,
			color: customColor.color || v.color,
			edge: customColor.edge || v.edge,
		});
	});
	return colors;
}

const colorData = buildColorTable();

interface Props {
	onOk: (colorCode: number) => void;
	onCancel: () => void;
	onClose: () => void;
}

export default function LdColorPickerDialog({
	onOk,
	onCancel,
	onClose,
}: Props) {
	function pick(colorCode: number) {
		onOk(colorCode);
	}

	return (
		<Dialog
			open
			onClose={onClose}
			maxWidth={false}
			className="ldColorPickerDialog"
			PaperProps={{ style: { width: "500px" } }}
		>
			<DialogTitle>{tr("dialog.ld_color_picker.title")}</DialogTitle>
			<DialogContent style={{ maxHeight: "70vh" }}>
				<table style={{ tableLayout: "fixed", width: "100%" }}>
					<thead>
						<tr>
							<th style={{ width: 100 }}>
								{tr("dialog.ld_color_picker.ld_code")}
							</th>
							<th style={{ width: 140, textAlign: "left" }}>
								{tr("dialog.ld_color_picker.name")}
							</th>
							<th style={{ width: 50, textAlign: "left" }}>
								{tr("dialog.ld_color_picker.choose")}
							</th>
						</tr>
					</thead>
				</table>
				<div
					style={{
						maxHeight: "64vh",
						overflowX: "hidden",
						overflowY: "scroll",
					}}
				>
					<table style={{ tableLayout: "fixed", width: "100%" }}>
						<tbody>
							{colorData.map((row) => (
								<tr key={row.id} style={{ height: 44 }}>
									<td style={{ width: 100, textAlign: "center" }}>{row.id}</td>
									<td style={{ width: 140, textAlign: "left" }}>
										{_.startCase(row.name)}
									</td>
									<td style={{ width: 50, textAlign: "center" }}>
										<div
											onClick={() => pick(row.id)}
											style={{
												width: 30,
												height: 30,
												border: "1px solid #ccc",
												borderRadius: 4,
												padding: 3,
												marginLeft: 20,
												cursor: "pointer",
											}}
										>
											<div
												style={{
													width: "100%",
													height: "100%",
													backgroundColor: row.color,
													border: "1px solid #999",
													borderRadius: 2,
												}}
											/>
										</div>
									</td>
								</tr>
							))}
						</tbody>
					</table>
				</div>
			</DialogContent>
			<DialogActions>
				<Button variant="cancel" onClick={onCancel} />
			</DialogActions>
		</Dialog>
	);
}

// src/dialogs/ld_color_picker.vue
/* Web Lic - Copyright (C) 2018 Remi Gagne */

<template>
	<LicDialog :title="t('dialog.ld_color_picker.title')" class="ldColorPickerDialog" width="500px">
		<table class="el-table brickColorTable">
			<thead>
				<tr>
					<th>{{ t('dialog.ld_color_picker.ld_code') }}</th>
					<th style="text-align: left">
						{{ t('dialog.ld_color_picker.name') }}
					</th>
					<th style="text-align: left">
						{{ t('dialog.ld_color_picker.choose') }}
					</th>
				</tr>
			</thead>
		</table>
		<div class="brickColorTableScroll">
			<table class="el-table brickColorTable">
				<tbody>
					<tr v-for="row in colorData" :key="row.id" class="brickColorRow">
						<td>{{ row.id }}</td>
						<td style="text-align: left">
							{{ _.startCase(row.name) }}
						</td>
						<td>
							<div class="swatch" @click="pick(row.id)">
								<div :style="{ 'background-color': row.color }" class="inner_swatch" />
							</div>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
		<template #footer>
			<LicButton type="cancel" @click="emit('cancel')" />
		</template>
	</LicDialog>
</template>

<script setup lang="ts">
import { t } from '@/translations';
import { ref } from 'vue';

import LicButton from '@/components/base/LicButton.vue';
import LicDialog from '@/components/base/LicDialog.vue';

import LDParse from '../ld_parse';
import Storage from '../storage';
import _ from '../util';

const emit = defineEmits<{
	(e: 'ok', colorCode: number): void;
	(e: 'cancel'): void;
}>();

const customColors = Storage.get.customBrickColors();

function buildColorTable() {
	const colors: { id: number; name: string; color: string; edge: string }[] = [];
	_.forOwn(LDParse.colorTable, (v, k) => {
		if (v.color < 0 || v.edge < 0) {
			return;
		}
		const id = parseInt(k, 10);
		const customColor = customColors[id] || {};
		colors.push({
			id,
			name: v.name,
			color: customColor.color || v.color,
			edge: customColor.edge || v.edge,
		});
	});
	return colors;
}

const colorData = ref(buildColorTable());

function pick(colorCode: number) {
	emit('ok', colorCode);
}
</script>

<style>
.ldColorPickerDialog {
	table-layout: fixed;
}

.ldColorPickerDialog td:nth-of-type(1),
.ldColorPickerDialog th:nth-of-type(1) {
	width: 100px;
}

.ldColorPickerDialog td:nth-of-type(2),
.ldColorPickerDialog th:nth-of-type(2) {
	width: 140px;
}

.ldColorPickerDialog td:nth-of-type(3),
.ldColorPickerDialog th:nth-of-type(3) {
	width: 50px;
}

.ldColorPickerDialog .swatch {
	width: 30px;
	height: 30px;
	border: 1px solid #ccc;
	border-radius: 4px;
	padding: 3px;
	margin-left: 20px;
	cursor: pointer;
}

.ldColorPickerDialog .inner_swatch {
	width: 100%;
	height: 100%;
	border: 1px solid #999;
	border-radius: 2px;
}

.brickColorTableScroll {
	max-height: 55vh;
	overflow-x: hidden;
	overflow-y: scroll;
}

.ldColorPickerDialog .el-table th,
.ldColorPickerDialog .el-table td {
	padding: 5px 0;
	text-align: center;
	overflow: hidden;
}
</style>
