// src/dialogs/missing_parts.tsx
/* Web Lic - Copyright (C) 2018 Remi Gagne */

import React, { useState } from "react";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogTitle from "@mui/material/DialogTitle";
import Tooltip from "@mui/material/Tooltip";

import { Button } from "../components/button";

import openFileHandler from "../file_uploader";
import LDParse from "../ld_parse";
import { tr } from "../translations";
import _ from "../util";

interface MissingPartEntry {
	uploaded: boolean;
	count: number;
}

function buildMissingPartsTable(): Record<string, MissingPartEntry> {
	const missingParts = _.cloneDeep(LDParse.missingParts);
	const result: Record<string, MissingPartEntry> = {};
	_.forOwn(missingParts, (value: number, key: string) => {
		result[key] = { uploaded: false, count: value };
	});
	return result;
}

interface Props {
	onClose: () => void;
}

export default function MissingPartsDialog({ onClose }: Props) {
	const [missingPartsData, setMissingPartsData] = useState(
		buildMissingPartsTable
	);
	const [loadedPartContent, setLoadedPartContent] = useState<
		Record<string, string | null>
	>({});
	const enablePartSend = window.location.host
		.toLowerCase()
		.includes("bugeyedmonkeys");

	const stillHaveMissingParts = _.some(missingPartsData, (p) => !p.uploaded);

	function ok() {
		if (stillHaveMissingParts) {
			LDParse.model.removeMissingParts();
		}
		onClose();
	}

	function upload(filename: string) {
		openFileHandler(
			".dat, .ldr, .mpd",
			"text",
			(content: string | ArrayBuffer | null) => {
				LDParse.loadPartContent(filename, content as string).then(() => {
					setLoadedPartContent((prev) => ({
						...prev,
						[filename]: content as string,
					}));
					setMissingPartsData((prev) => {
						const next = {
							...prev,
							[filename]: { ...prev[filename], uploaded: true },
						};
						_.each(LDParse.missingParts, (count: number, fn: string) => {
							if (!(fn in next)) {
								next[fn] = { uploaded: false, count };
							}
						});
						return next;
					});
				});
			}
		);
	}

	function sendToRemote(filename: string) {
		if (enablePartSend) {
			const xhr = new XMLHttpRequest();
			xhr.open("POST", "http://bugeyedmonkeys.com/lic/upload_part.php", true);
			xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
			const content = `&content=filename: ${filename}\n-----\n${loadedPartContent[filename]}\n-----`;
			xhr.send(content);
		}
		setLoadedPartContent((prev) => ({ ...prev, [filename]: null }));
	}

	function showSendButton(filename: string): boolean {
		return (
			!!missingPartsData[filename]?.uploaded &&
			enablePartSend &&
			loadedPartContent[filename] != null
		);
	}

	const okText = stillHaveMissingParts
		? tr("dialog.missing_parts.proceed")
		: tr("dialog.ok");

	return (
		<Dialog
			open
			onClose={onClose}
			maxWidth={false}
			className="missingPartsDialog"
			PaperProps={{ style: { width: "550px" } }}
		>
			<DialogTitle>{tr("dialog.missing_parts.title")}</DialogTitle>
			<DialogContent style={{ maxHeight: "70vh" }}>
				<div
					className="subheading"
					style={{
						paddingBottom: 20,
						borderBottom: "1px solid #ddd",
						marginBottom: 20,
					}}
					dangerouslySetInnerHTML={{
						__html: tr("dialog.missing_parts.subtitle"),
					}}
				/>
				<table
					className="missingPartsTable"
					style={{ tableLayout: "fixed", width: "100%" }}
				>
					<tbody>
						{Object.entries(missingPartsData).map(([filename, value]) => (
							<tr key={filename} style={{ height: 50 }}>
								<td style={{ textAlign: "right" }}>
									{value.uploaded && (
										<i
											className="fas fa-check"
											style={{ color: "#00c700", marginRight: 10 }}
										/>
									)}
									{filename}
								</td>
								<td style={{ width: 125, textAlign: "center" }}>
									{tr("dialog.missing_parts.used_@mf", { count: value.count })}
								</td>
								<td style={{ width: 200, textAlign: "center" }}>
									{showSendButton(filename) ? (
										<Tooltip
											title={
												<span
													dangerouslySetInnerHTML={{
														__html: tr(
															"dialog.missing_parts.send_to_remote.tooltip"
														),
													}}
												/>
											}
										>
											<Button wide onClick={() => sendToRemote(filename)}>
												{tr("dialog.missing_parts.send_to_remote.title")}
											</Button>
										</Tooltip>
									) : !value.uploaded ? (
										<Button wide onClick={() => upload(filename)}>
											{tr("glossary.import")}
										</Button>
									) : null}
								</td>
							</tr>
						))}
					</tbody>
				</table>
			</DialogContent>
			<DialogActions>
				<Button wide onClick={ok}>
					{okText}
				</Button>
			</DialogActions>
		</Dialog>
	);
}

// src/dialogs/missing_parts.vue
/* Web Lic - Copyright (C) 2018 Remi Gagne */

<template>
	<LicDialog :title="t('dialog.missing_parts.title')" class="missingPartsDialog" width="550px">
		<div class="subheading" v-html="t('dialog.missing_parts.subtitle')" />
		<table class="missingPartsTable">
			<tbody>
				<tr v-for="(value, filename) in missingPartsData" :key="filename" class="missingPartRow">
					<td>
						<i v-if="value.uploaded" class="fas fa-check" />
						{{ filename }}
					</td>
					<td>{{ partCount(value.count) }}</td>
					<td>
						<LicTooltip v-if="showSendButton(filename)">
							<template #content>
								<div v-html="t('dialog.missing_parts.send_to_remote.tooltip')" />
							</template>
							<LicButton @click="sendToRemote(filename)">
								{{ t('dialog.missing_parts.send_to_remote.title') }}
							</LicButton>
						</LicTooltip>
						<LicButton v-else-if="!value.uploaded" @click="upload(filename)">
							{{ t('glossary.import') }}
						</LicButton>
					</td>
				</tr>
			</tbody>
		</table>
		<template #footer>
			<LicButton type="primary" @click="ok">
				{{ okText }}
			</LicButton>
		</template>
	</LicDialog>
</template>

<script setup lang="ts">
import { t } from '@/translations';
import { computed, ref } from 'vue';

import LicButton from '@/components/base/LicButton.vue';
import LicDialog from '@/components/base/LicDialog.vue';
import LicTooltip from '@/components/base/LicTooltip.vue';

import openFileHandler from '../file_uploader';
import LDParse from '../ld_parse';
import _ from '../util';

const emit = defineEmits<{ (e: 'ok'): void; (e: 'cancel'): void }>();

type PartEntry = { uploaded: boolean; count: number };
type MissingPartsData = Record<string, PartEntry>;
type LoadedContent = Record<string, string | null>;

function buildMissingPartsTable(): MissingPartsData {
	const missingParts = _.cloneDeep(LDParse.missingParts);
	const result: MissingPartsData = {};
	_.forOwn(missingParts, (value: number, key: string) => {
		result[key] = { uploaded: false, count: value };
	});
	return result;
}

const enablePartSend = window.location.host.toLowerCase().includes('bugeyedmonkeys');
const missingPartsData = ref<MissingPartsData>(buildMissingPartsTable());
const loadedPartContent = ref<LoadedContent>({});

const stillHaveMissingParts = computed(() => _.some(missingPartsData.value, (p) => !p.uploaded));

const okText = computed(() =>
	stillHaveMissingParts.value ? t('dialog.missing_parts.proceed') : t('dialog.ok'),
);

function partCount(count: number) {
	return t('dialog.missing_parts.used_@mf', { count });
}

function showSendButton(filename: string) {
	return (
		missingPartsData.value[filename].uploaded &&
		enablePartSend &&
		loadedPartContent.value[filename] != null
	);
}

function ok() {
	if (stillHaveMissingParts.value) {
		LDParse.model.removeMissingParts();
	}
	emit('ok');
}

function upload(filename: string) {
	openFileHandler('.dat, .ldr, .mpd', 'text', (content: string | ArrayBuffer | null) => {
		LDParse.loadPartContent(content as string).then(() => {
			loadedPartContent.value = {
				...loadedPartContent.value,
				[filename]: content as string | null,
			};
			missingPartsData.value[filename].uploaded = true;
			_.each(LDParse.missingParts, (count: number, fn: string) => {
				if (!(fn in missingPartsData.value)) {
					missingPartsData.value = {
						...missingPartsData.value,
						[fn]: { uploaded: false, count },
					};
				}
			});
		});
	});
}

function sendToRemote(filename: string) {
	if (enablePartSend) {
		const xhr = new XMLHttpRequest();
		xhr.open('POST', 'http://bugeyedmonkeys.com/lic/upload_part.php', true);
		xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
		const content =
			`&content=filename: ${filename}\n` +
			'------------------------------\n' +
			`${loadedPartContent.value[filename]}\n` +
			'------------------------------';
		xhr.send(content);
	}
	loadedPartContent.value[filename] = null;
}
</script>

<style>
.missingPartsDialog {
	.subheading {
		padding-bottom: 20px;
		border-bottom: 1px solid #ddd;
		margin-bottom: 20px;
	}

	.body {
		max-height: 70vh;
	}
}

.missingPartsTable {
	table-layout: fixed;
	width: 100%;

	tr {
		height: 50px;
	}

	td {
		text-align: center;
	}

	i {
		color: #00c700;
		margin-right: 10px;
	}

	td:nth-of-type(1) {
		text-align: right;
	}

	td:nth-of-type(2) {
		width: 125px;
	}

	td:nth-of-type(3) {
		width: 200px;
	}
}
</style>
