// src/dialogs/page_layout.tsx
/* Web Lic - Copyright (C) 2018 Remi Gagne */

import React, { useEffect, useState } from "react";
import Checkbox from "@mui/material/Checkbox";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogTitle from "@mui/material/DialogTitle";
import FormControlLabel from "@mui/material/FormControlLabel";
import Radio from "@mui/material/Radio";
import RadioGroup from "@mui/material/RadioGroup";

import { Button } from "../components/button";

import EventBus from "../event_bus";
import type { GridLayout, LookupItem, Orientations } from "../item_types";
import store from "../store";
import { tr } from "../translations";
import undoStack from "../undo_stack";

interface Props {
	_showArg: { values: GridLayout; page: LookupItem };
	onClose: () => void;
}

export default function PageLayoutDialog({ _showArg, onClose }: Props) {
	const [rows, setRows] = useState(1);
	const [autoRows, setAutoRows] = useState(true);
	const [cols, setCols] = useState(1);
	const [autoCols, setAutoCols] = useState(true);
	const [direction, setDirection] = useState<Orientations>("horizontal");

	const initialValues = _showArg.values;

	useEffect(() => {
		if (initialValues.rows !== rows && initialValues.rows !== "auto") {
			setRows(initialValues.rows);
		}
		if (
			(initialValues.rows === "auto" && !autoRows) ||
			(initialValues.rows !== "auto" && autoRows)
		) {
			setAutoRows(initialValues.rows === "auto");
		}

		if (initialValues.cols !== cols && initialValues.cols !== "auto") {
			setCols(initialValues.cols);
		}
		if (
			(initialValues.cols === "auto" && !autoCols) ||
			(initialValues.cols !== "auto" && autoCols)
		) {
			setAutoCols(initialValues.cols === "auto");
		}

		if (initialValues.direction !== direction) {
			setDirection(initialValues.direction);
		}
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, []);

	function update(values: GridLayout) {
		store.mutations.page.layout({ page: _showArg.page, layout: values });
		EventBus.emit("redraw-ui", undefined);
	}

	function onOk() {
		undoStack.commit(
			"page.layout",
			{
				page: _showArg.page,
				layout: {
					rows: autoRows ? "auto" : rows,
					cols: autoCols ? "auto" : cols,
					direction,
				},
			},
			tr("action.layout.by_row_and_column.undo")
		);
		onClose();
	}

	function onCancel() {
		console.log("cancelling, reverting to: ", _showArg.values);
		store.mutations.page.layout({
			page: _showArg.page,
			layout: _showArg.values,
		});
		EventBus.emit("redraw-ui", undefined);
		onClose();
	}

	return (
		<Dialog
			open
			onClose={onClose}
			maxWidth={false}
			className="pageLayoutDialog"
			PaperProps={{ style: { width: "500px" } }}
		>
			<DialogTitle>{tr("dialog.page_layout.title")}</DialogTitle>
			<DialogContent>
				<div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
					<div style={{ display: "flex", alignItems: "center", gap: 8 }}>
						<label style={{ width: 100 }}>
							{tr("dialog.page_layout.rows")}
						</label>
						<FormControlLabel
							className="el-checkbox"
							control={
								<Checkbox
									checked={autoRows}
									onChange={(e) => {
										console.log("auto rows CHECKED: ", e.target.checked);
										setAutoRows(e.target.checked);
										update({
											rows: e.target.checked ? "auto" : rows,
											cols: autoCols ? "auto" : cols,
											direction,
										});
									}}
								/>
							}
							label={tr("glossary.auto")}
						/>
						<input
							type="number"
							min={1}
							className="form-control"
							value={rows}
							disabled={autoRows}
							style={{ width: 90 }}
							onChange={(e) => {
								const newRows = parseInt(e.target.value, 10);
								setRows(newRows);
								update({
									rows: newRows,
									cols: autoCols ? "auto" : cols,
									direction,
								});
							}}
						/>
					</div>
					<div style={{ display: "flex", alignItems: "center", gap: 8 }}>
						<label style={{ width: 100 }}>
							{tr("dialog.page_layout.cols")}
						</label>
						<FormControlLabel
							className="el-checkbox"
							control={
								<Checkbox
									checked={autoCols}
									onChange={(e) => {
										setAutoCols(e.target.checked);
										update({
											rows: autoRows ? "auto" : rows,
											cols: e.target.checked ? "auto" : cols,
											direction,
										});
									}}
								/>
							}
							label={tr("glossary.auto")}
						/>
						<input
							type="number"
							min={1}
							className="form-control"
							value={cols}
							disabled={autoCols}
							style={{ width: 90 }}
							onChange={(e) => {
								const newCols = parseInt(e.target.value, 10);
								setCols(newCols);
								update({
									rows: autoRows ? "auto" : rows,
									cols: newCols,
									direction,
								});
							}}
						/>
					</div>
					<div style={{ display: "flex", alignItems: "center", gap: 8 }}>
						<label style={{ width: 100 }}>
							{tr("dialog.page_layout.orientation")}
						</label>
						<RadioGroup
							row
							value={direction}
							onChange={(e) => {
								const newDirection = e.target.value;
								if (
									newDirection === "horizontal" ||
									newDirection === "vertical"
								) {
									setDirection(newDirection);
									update({
										rows: autoRows ? "auto" : rows,
										cols: autoCols ? "auto" : cols,
										direction: newDirection,
									});
								}
							}}
						>
							<FormControlLabel
								value="horizontal"
								control={<Radio />}
								label={tr("dialog.page_layout.horizontal")}
								className="el-radio"
							/>
							<FormControlLabel
								value="vertical"
								control={<Radio />}
								label={tr("dialog.page_layout.vertical")}
								className="el-radio"
							/>
						</RadioGroup>
					</div>
				</div>
			</DialogContent>
			<DialogActions>
				<Button variant="cancel" onClick={onCancel} />
				<Button variant="ok" onClick={onOk} />
			</DialogActions>
		</Dialog>
	);
}

// src/dialogs/page_layout.vue
/* Web Lic - Copyright (C) 2018 Remi Gagne */

<template>
	<LicDialog
		:title="t('dialog.page_layout.title')"
		width="400px"
		class="pageLayoutDialog"
	>
		<div class="flex-row panel-row">
			<span class="page-layout-label">{{t('dialog.page_layout.rows')}}</span>
			<label class="lic-checkbox">
				<input v-model="autoRows" type="checkbox" @change="updateValues">
				{{t('glossary.auto')}}
			</label>
			<input
				v-model.number="values.rows"
				:disabled="autoRows"
				type="number"
				min="1"
				class="form-control"
				@input="updateValues"
			>
		</div>
		<div class="flex-row panel-row">
			<span class="page-layout-label">{{t('dialog.page_layout.cols')}}</span>
			<label class="lic-checkbox">
				<input v-model="autoCols" type="checkbox" @change="updateValues">
				{{t('glossary.auto')}}
			</label>
			<input
				v-model.number="values.cols"
				:disabled="autoCols"
				type="number"
				min="1"
				class="form-control"
				@input="updateValues"
			>
		</div>
		<div class="flex-row panel-row">
			<span class="page-layout-label">{{t('dialog.page_layout.orientation')}}</span>
			<label class="lic-radio">
				<input
					type="radio"
					name="direction"
					value="horizontal"
					:checked="values.direction === 'horizontal'"
					@change="setDirection('horizontal')"
				>
				{{t('dialog.page_layout.horizontal')}}
			</label>
			<label class="lic-radio">
				<input
					type="radio"
					name="direction"
					value="vertical"
					:checked="values.direction === 'vertical'"
					@change="setDirection('vertical')"
				>
				{{t('dialog.page_layout.vertical')}}
			</label>
		</div>
		<template #footer>
			<LicButton type="cancel" @click="cancel" />
			<LicButton type="ok" @click="ok" />
		</template>
	</LicDialog>
</template>

<script setup lang="ts">

import {ref, reactive, computed} from 'vue';
import {t} from '@/translations';
import LicDialog from '@/components/base/LicDialog.vue';
import LicButton from '@/components/base/LicButton.vue';
import {type GridLayout, type Orientations} from '../item_types';

const props = defineProps<{initialLayout: GridLayout}>();
// eslint-disable-next-line max-len
const emit = defineEmits<{(e: 'update', v: GridLayout): void; (e: 'ok', v: GridLayout): void; (e: 'cancel'): void}>();

const autoRows = ref(props.initialLayout.rows === 'auto');
const autoCols = ref(props.initialLayout.cols === 'auto');
const values = reactive({
	rows: props.initialLayout.rows === 'auto' ? 1 : props.initialLayout.rows as number,
	cols: props.initialLayout.cols === 'auto' ? 1 : props.initialLayout.cols as number,
	direction: props.initialLayout.direction,
});

const actualValues = computed<GridLayout>(() => ({
	rows: autoRows.value ? 'auto' : values.rows,
	cols: autoCols.value ? 'auto' : values.cols,
	direction: values.direction,
}));

function setDirection(dir: Orientations) {
	values.direction = dir;
	updateValues();
}

function updateValues() {
	emit('update', actualValues.value);
}

function ok() {
	emit('ok', actualValues.value);
}

function cancel() {
	emit('cancel');
}

</script>

<style>

.pageLayoutDialog {
	input {
		width: 90px;
	}
}

.page-layout-label {
	width: 80px;
	flex-shrink: 0;
}

</style>
