// src/dialogs/rotate_part_image.tsx
/* Web Lic - Copyright (C) 2018 Remi Gagne */

import React, { useState } from "react";
import Checkbox from "@mui/material/Checkbox";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogTitle from "@mui/material/DialogTitle";
import FormControlLabel from "@mui/material/FormControlLabel";

import { Button } from "../components/button";
import Rotate from "../components/rotate";

import type { Rotation } from "../item_types";
import { tr } from "../translations";
import _ from "../util";

interface Props {
	title?: string;
	addRotateIcon?: boolean;
	showRotateIconCheckbox?: boolean;
	initialRotation?: Rotation[];
	onOk: (v: any) => void;
	onCancel: (v: any) => void;
	onUpdate?: (v: any) => void;
	onClose: () => void;
}

export default function RotatePartImageDialog({
	title: titleProp = "",
	addRotateIcon: addIconProp = true,
	showRotateIconCheckbox = true,
	initialRotation = [],
	onOk,
	onCancel,
	onUpdate,
	onClose,
}: Props) {
	const [rotation, setRotation] = useState<Rotation[]>(
		_.cloneDeep(initialRotation)
	);
	const [addRotateIcon, setAddRotateIcon] = useState(addIconProp);

	function getData() {
		return {
			title: titleProp,
			rotation,
			addRotateIcon,
			showRotateIconCheckbox,
			initialRotation,
		};
	}

	function updateValues(newRotation?: Rotation[]) {
		const r =
			newRotation && Array.isArray(newRotation) ? newRotation : rotation;
		if (newRotation && Array.isArray(newRotation)) {
			setRotation(r);
		}
		onUpdate?.({ ...getData(), rotation: r });
	}

	return (
		<Dialog
			open
			onClose={onClose}
			maxWidth={false}
			className="rotatePartImageDialog"
			PaperProps={{ style: { width: "400px" } }}
		>
			<DialogTitle>{titleProp}</DialogTitle>
			<DialogContent>
				<Rotate
					title=""
					initialRotation={rotation}
					includeLabels={false}
					onNewValues={updateValues}
				/>
				{showRotateIconCheckbox && (
					<FormControlLabel
						className="el-checkbox"
						control={
							<Checkbox
								checked={addRotateIcon}
								onChange={(e) => {
									setAddRotateIcon(e.target.checked);
									updateValues();
								}}
								data-testid="rotate-add-icon"
							/>
						}
						label={tr("dialog.rotate_part_image.add_rotate_icon")}
					/>
				)}
			</DialogContent>
			<DialogActions>
				<Button
					variant="outlined"
					onClick={() => onCancel(getData())}
					data-testid="rotate-cancel"
				>
					{tr("dialog.cancel")}
				</Button>
				<Button onClick={() => onOk(getData())} data-testid="rotate-ok">
					{tr("dialog.ok")}
				</Button>
			</DialogActions>
		</Dialog>
	);
}

// src/dialogs/rotate_part_image.vue
/* Web Lic - Copyright (C) 2018 Remi Gagne */

<template>
	<licDialog
		:title="title"
		width="400px"
		class="rotatePartImageDialog"
	>
		<el-form :inline="true" label-width="50px">
			<rotate-builder
				:initial-rotation="rotation"
				title=""
				@new-values="updateValues"
			/>
		</el-form>
		<el-form v-if="showRotateIconCheckbox" :inline="true" label-width="180px">
			<el-form-item>
				<el-checkbox
					v-model="addRotateIcon"
					data-testid="rotate-add-icon"
					@change="updateValues"
				>
					{{tr('dialog.rotate_part_image.add_rotate_icon')}}
				</el-checkbox>
			</el-form-item>
		</el-form>
		<span slot="footer" class="dialog-footer">
			<el-button data-testid="rotate-cancel" @click="cancel">{{tr("dialog.cancel")}}</el-button>
			<el-button type="primary" data-testid="rotate-ok" @click="ok()">{{tr("dialog.ok")}}</el-button>
		</span>
	</licDialog>
</template>

<script>

import _ from '../util';
import rotateBuilder from '../components/rotate.vue';

export default {
	components: {rotateBuilder},
	data: function() {
		return {
			title: '',
			addRotateIcon: true,
			showRotateIconCheckbox: true,
			initialRotation: [],
		};
	},
	methods: {
		updateValues(newRotation) {
			if (newRotation && Array.isArray(newRotation)) {
				this.$data.rotation = newRotation;
			}
			this.$emit('update', this.$data);
		},
		ok() {
			this.$emit('ok', this.$data);
			this.$emit('close');
		},
		cancel() {
			this.$emit('cancel', this.$data);
			this.$emit('close');
		},
	},
	computed: {
		rotation: {
			get() {
				return this.initialRotation;
			},
			set(newRotation) {
				this.$data.rotation = this.initialRotation = _.cloneDeep(newRotation);
			},
		},
	},
};
</script>

<style>

.rotatePartImageDialog .el-checkbox {
	font-weight: 700;
}

</style>
