// src/dialogs/string_chooser.tsx
/* Web Lic - Copyright (C) 2018 Remi Gagne */

import React, { useEffect, useRef, useState } from "react";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogTitle from "@mui/material/DialogTitle";

import { Button } from "../components/button";

interface Props {
	title?: string;
	label?: string;
	width?: string;
	newString?: string;
	onOk: (value: string) => void;
	onCancel: () => void;
	onUpdate?: (value: any) => void;
	onClose: () => void;
}

export default function StringChooserDialog({
	title = "",
	label = "",
	width = "500px",
	newString: initialString = "",
	onOk,
	onCancel,
	onClose,
	onUpdate,
}: Props) {
	const [value, setValue] = useState(initialString ?? "");
	const inputRef = useRef<HTMLInputElement>(null);

	useEffect(() => {
		inputRef.current?.focus();
	}, []);

	function ok() {
		onOk(value);
	}

	function cancel() {
		onCancel();
	}

	return (
		<Dialog
			open
			onClose={onClose}
			maxWidth={false}
			PaperProps={{ style: { width } }}
		>
			<DialogTitle>{title}</DialogTitle>
			<DialogContent>
				<div style={{ display: "flex", alignItems: "center", gap: 8 }}>
					{label && <label>{label}</label>}
					<input
						ref={inputRef}
						className="form-control"
						value={value}
						style={{ flexGrow: 1 }}
						onChange={(e) => {
							setValue(e.target.value);
							onUpdate?.({ newString: e.target.value });
						}}
					/>
				</div>
			</DialogContent>
			<DialogActions>
				<Button variant="cancel" onClick={cancel} />
				<Button variant="ok" onClick={ok} />
			</DialogActions>
		</Dialog>
	);
}

// src/dialogs/string_chooser.vue
/* Web Lic - Copyright (C) 2018 Remi Gagne */

<template>
	<LicDialog :title="title" :width="width ?? '500px'">
		<label class="label-input-row">
			{{label}}
			<input ref="set_focus" v-model="newString" class="form-control">
		</label>
		<template #footer>
			<LicButton type="cancel" @click="cancel" />
			<LicButton type="ok" @click="ok" />
		</template>
	</LicDialog>
</template>

<script setup lang="ts">

import {ref} from 'vue';
import LicDialog from '@/components/base/LicDialog.vue';
import LicButton from '@/components/base/LicButton.vue';

const props = defineProps<{title: string; label: string; initialValue?: string | null; width?: string}>();
const emit = defineEmits<{(e: 'ok', value: string): void; (e: 'cancel'): void}>();

const newString = ref(props.initialValue ?? '');

function ok() {
	emit('ok', newString.value);
}

function cancel() {
	emit('cancel');
}

</script>
