// src/dialogs/style.tsx
/* Web Lic - Copyright (C) 2018 Remi Gagne */

import React, { useEffect, useState } from "react";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogTitle from "@mui/material/DialogTitle";
import MenuItem from "@mui/material/MenuItem";
import Select, { type SelectChangeEvent } from "@mui/material/Select";

import { Button } from "../components/button";

import { tr } from "../translations";
import _ from "../util";
import { addCustomFont, getFamilyNames } from "./font_utils";

interface StyleDialogProps {
	title?: string;
	text?: string;
	color?: string;
	font?: string;
	onOk: (v: { text: string; font: string; color: string }) => void;
	onCancel: () => void;
	onClose: () => void;
}

export default function StyleDialog({
	title: titleProp,
	text: textProp = "",
	color: colorProp = "",
	font: fontProp = "",
	onOk,
	onCancel,
	onClose,
}: StyleDialogProps) {
	const [title] = useState(titleProp || tr("dialog.style.title"));
	const [text, setText] = useState(textProp);
	const [color, setColor] = useState("");
	const [family, setFamily] = useState("");
	const [size, setSize] = useState(0);
	const [bold, setBold] = useState(false);
	const [italic, setItalic] = useState(false);
	const familyNames = getFamilyNames();

	useEffect(() => {
		const parsedColor = _.color.toRGB(colorProp).toString();
		setColor(parsedColor);
		const fontParts = _.fontToFontParts(fontProp);
		addCustomFont(fontParts.fontFamily || "");
		setFamily(fontParts.fontFamily || "");
		setSize(parseInt(fontParts.fontSize || "14px", 10));
		setBold(fontParts.fontWeight === "bold");
		setItalic(fontParts.fontStyle === "italic");
	}, [colorProp, fontProp]);

	function ok() {
		onOk({
			text,
			font: _.fontString({
				family,
				size,
				bold: bold ? "bold" : "",
				italic: italic ? "italic" : "",
			}),
			color,
		});
	}

	return (
		<Dialog
			open
			onClose={onClose}
			maxWidth={false}
			className="styleDialog"
			PaperProps={{ style: { width: "500px" } }}
		>
			<DialogTitle>{title}</DialogTitle>
			<DialogContent>
				<div
					style={{
						display: "grid",
						gridTemplateColumns: "100px 1fr",
						gap: 8,
						alignItems: "start",
					}}
				>
					<label>{tr("dialog.style.label_text")}</label>
					<textarea
						rows={2}
						className="form-control"
						value={text}
						onChange={(e) => setText(e.target.value)}
					/>
					<label>{tr("glossary.font")}</label>
					<div
						style={{
							display: "flex",
							alignItems: "center",
							gap: 4,
							flexWrap: "wrap",
						}}
					>
						<Select
							value={family}
							className="form-dropdown"
							onChange={(e: SelectChangeEvent) => setFamily(e.target.value)}
						>
							{familyNames.map((group) =>
								group.options.map((font) => (
									<MenuItem key={font} value={font}>
										{font}
									</MenuItem>
								))
							)}
						</Select>
						<Button
							variant={bold ? null : "outlined"}
							onClick={() => setBold((b) => !b)}
						>
							<strong>B</strong>
						</Button>
						<Button
							variant={italic ? null : "outlined"}
							onClick={() => setItalic((i) => !i)}
						>
							<em>I</em>
						</Button>
					</div>
					<label>{tr("glossary.font_size")}</label>
					<input
						type="number"
						className="form-control"
						min={0}
						value={size}
						style={{ width: 75 }}
						onChange={(e) => setSize(parseInt(e.target.value, 10))}
					/>
					<label>{tr("glossary.color")}</label>
					<input
						type="color"
						value={color}
						onChange={(e) => setColor(e.target.value)}
						className="form-control color-picker-button"
					/>
				</div>
			</DialogContent>
			<DialogActions>
				<Button variant="outlined" onClick={onCancel}>
					{tr("dialog.cancel")}
				</Button>
				<Button onClick={ok}>{tr("dialog.ok")}</Button>
			</DialogActions>
		</Dialog>
	);
}

// src/dialogs/style.vue
/* Web Lic - Copyright (C) 2018 Remi Gagne */

<template>
	<licDialog
		:title="title"
		class="styleDialog"
		width="500px"
	>
		<el-form label-width="100px">
			<el-form-item :label="tr('dialog.style.label_text')">
				<el-input
					v-model="text"
					:rows="2"
					type="textarea"
				/>
			</el-form-item>
			<el-form-item :label="tr('glossary.font')">
				<el-select
					v-model="family"
				>
					<el-option-group v-for="group in familyNames" :key="group.label">
						<el-option
							v-for="fontItem in group.options"
							:key="fontItem"
							:value="fontItem"
						>
							{{fontItem}}
						</el-option>
					</el-option-group>
				</el-select>
				<el-checkbox-button
					v-model="bold"
					class="fontStyleButton"
				>
					<strong>B</strong>
				</el-checkbox-button>
				<el-checkbox-button
					v-model="italic"
					class="fontStyleButton"
				>
					<em>I</em>
				</el-checkbox-button>
				<!-- <el-checkbox-button
					v-model="underline"
					class="fontStyleButton"
				>
					<u>U</u>
				</el-checkbox-button> -->
			</el-form-item>
			<el-form-item :label="tr('glossary.font_size')">
				<input
					v-model.number="size"
					type="number"
					min="0"
					class="form-control size-input"
				>
			</el-form-item>
			<el-form-item :label="tr('glossary.color')">
				<el-color-picker
					v-model="color"
					show-alpha
				/>
			</el-form-item>
		</el-form>
		<span slot="footer">
			<lic-button type="cancel" @click="cancel" />
			<lic-button type="ok" @click="ok" />
		</span>
	</licDialog>
</template>

<script>

import _ from '../util';
import fontNameDialog from './font_name.vue';

export default {
	data: function() {
		return {
			title: this.tr('dialog.style.title'),
			text: '',
			color: '',
			font: '',
			family: '',
			size: 0,
			bold: false,
			italic: false,
			underline: false,
		};
	},
	methods: {
		show() {
			this.color = _.color.toRGB(this.color).toString();
			const fontParts = _.fontToFontParts(this.font);
			fontNameDialog.methods.addCustomFont(fontParts.fontFamily);
			this.family = fontParts.fontFamily;
			this.size = parseInt(fontParts.fontSize, 10);
			this.bold = fontParts.fontWeight === 'bold';
			this.italic = fontParts.fontStyle === 'italic';
			this.underline = false;
		},
		ok() {
			this.$emit('ok', {
				text: this.text,
				font: _.fontString(this),
				color: this.color,
			});
			this.$emit('close');
		},
		cancel() {
			this.$emit('close');
		},
	},
	computed: {
		familyNames: fontNameDialog.methods.getFamilyNames,
	},
};
</script>

<style>

.styleDialog .size-input {
	width: 75px;
}

</style>
