// src/dialogs/transform_part.vue
/* Web Lic - Copyright (C) 2018 Remi Gagne */

<template>
	<LicDialog
		:title="t('dialog.transform_part.title')"
		width="600px"
		class="transformPartDialog"
	>
		<div class="flex-row panel-row" style="gap: 30px;">
			<span class="transform-section">{{t('dialog.transform_part.position')}}</span>
			<label class="flex-row">{{t('glossary.x')}}
				<input
					ref="set_focus"
					v-model.number="position.x"
					type="number"
					class="form-control"
					@input="updateValues"
				>
			</label>
			<label class="flex-row">{{t('glossary.y')}}
				<input v-model.number="position.y" type="number" class="form-control" @input="updateValues">
			</label>
			<label class="flex-row">{{t('glossary.z')}}
				<input v-model.number="position.z" type="number" class="form-control" @input="updateValues">
			</label>
		</div>
		<div class="flex-row panel-row" style="gap: 30px;">
			<span class="transform-section">{{t('dialog.transform_part.rotation')}}</span>
			<label class="flex-row">{{t('glossary.x')}}
				<input v-model.number="rotation.x" type="number" class="form-control" @input="updateValues">
			</label>
			<label class="flex-row">{{t('glossary.y')}}
				<input v-model.number="rotation.y" type="number" class="form-control" @input="updateValues">
			</label>
			<label class="flex-row">{{t('glossary.z')}}
				<input v-model.number="rotation.z" type="number" class="form-control" @input="updateValues">
			</label>
		</div>
		<template #footer>
			<LicButton type="cancel" @click="cancel" />
			<LicButton type="ok" @click="ok" />
		</template>
	</LicDialog>
</template>

<script setup lang="ts">

import {ref} from 'vue';
import {t} from '@/translations';
import LicDialog from '@/components/base/LicDialog.vue';
import LicButton from '@/components/base/LicButton.vue';

const emit = defineEmits(['update', 'ok', 'cancel', 'close']);

const title = ref('');
const rotation = ref({x: 0, y: 0, z: 0});
const position = ref({x: 0, y: 0, z: 0});
const addRotateIcon = ref(true);
const showRotateIconCheckbox = ref(true);

defineExpose({title, rotation, position, addRotateIcon, showRotateIconCheckbox});

function currentProps() {
	return {
		title: title.value,
		rotation: rotation.value,
		position: position.value,
		addRotateIcon: addRotateIcon.value,
		showRotateIconCheckbox: showRotateIconCheckbox.value,
	};
}

function updateValues() {
	emit('update', currentProps());
}

function ok() {
	emit('ok', currentProps());
	emit('close');
}

function cancel() {
	emit('cancel');
	emit('close');
}

</script>

<style>

.transformPartDialog {
	input {
		width: 90px;
	}
}

.transform-section {
	width: 70px;
	flex-shrink: 0;
}

</style>

// src/dialogs/transform_part.tsx
/* Web Lic - Copyright (C) 2018 Remi Gagne */

import React, { useEffect, useRef, useState } from "react";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogTitle from "@mui/material/DialogTitle";

import { Button } from "../components/button";

import { tr } from "../translations";

interface Vec3 {
	x: number;
	y: number;
	z: number;
}

interface Props {
	title?: string;
	rotation?: Vec3;
	position?: Vec3;
	addRotateIcon?: boolean;
	showRotateIconCheckbox?: boolean;
	onOk: (v: any) => void;
	onCancel: (v: any) => void;
	onUpdate?: (v: any) => void;
	onClose: () => void;
}

export default function TransformPartDialog({
	title: titleProp = "",
	rotation: rotProp = { x: 0, y: 0, z: 0 },
	position: posProp = { x: 0, y: 0, z: 0 },
	addRotateIcon: addRotateIconProp = true,
	showRotateIconCheckbox: showCheckboxProp = true,
	onOk,
	onCancel,
	onUpdate,
	onClose,
}: Props) {
	const [rotation, setRotation] = useState<Vec3>(rotProp);
	const [position, setPosition] = useState<Vec3>(posProp);
	const [addRotateIcon] = useState(addRotateIconProp);
	const [showRotateIconCheckbox] = useState(showCheckboxProp);
	const inputRef = useRef<HTMLInputElement>(null);

	useEffect(() => {
		inputRef.current?.focus();
	}, []);

	function getData() {
		return {
			title: titleProp,
			rotation,
			position,
			addRotateIcon,
			showRotateIconCheckbox,
		};
	}

	function setPos(axis: "x" | "y" | "z", val: number) {
		const next = { ...position, [axis]: val };
		setPosition(next);
		onUpdate?.({
			title: titleProp,
			rotation,
			position: next,
			addRotateIcon,
			showRotateIconCheckbox,
		});
	}

	function setRot(axis: "x" | "y" | "z", val: number) {
		const next = { ...rotation, [axis]: val };
		setRotation(next);
		onUpdate?.({
			title: titleProp,
			rotation: next,
			position,
			addRotateIcon,
			showRotateIconCheckbox,
		});
	}

	function numInput(
		val: number,
		onChange: (v: number) => void,
		ref?: React.Ref<HTMLInputElement>
	) {
		return (
			<input
				ref={ref as any}
				type="number"
				className="form-control"
				value={val}
				style={{ width: 80 }}
				onChange={(e) => onChange(parseFloat(e.target.value) || 0)}
			/>
		);
	}

	return (
		<Dialog
			open
			onClose={onClose}
			maxWidth={false}
			className="transformPartDialog"
			PaperProps={{ style: { width: "600px" } }}
		>
			<DialogTitle>{tr("dialog.transform_part.title")}</DialogTitle>
			<DialogContent>
				<div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
					<div style={{ display: "flex", alignItems: "center", gap: 8 }}>
						<label style={{ width: 90 }}>
							{tr("dialog.transform_part.position")}
						</label>
						<label style={{ width: 40 }}>{tr("glossary.x")}</label>
						{numInput(position.x, (v) => setPos("x", v), inputRef)}
						<label style={{ width: 40 }}>{tr("glossary.y")}</label>
						{numInput(position.y, (v) => setPos("y", v))}
						<label style={{ width: 40 }}>{tr("glossary.z")}</label>
						{numInput(position.z, (v) => setPos("z", v))}
					</div>
					<div style={{ display: "flex", alignItems: "center", gap: 8 }}>
						<label style={{ width: 90 }}>
							{tr("dialog.transform_part.rotation")}
						</label>
						<label style={{ width: 40 }}>{tr("glossary.x")}</label>
						{numInput(rotation.x, (v) => setRot("x", v))}
						<label style={{ width: 40 }}>{tr("glossary.y")}</label>
						{numInput(rotation.y, (v) => setRot("y", v))}
						<label style={{ width: 40 }}>{tr("glossary.z")}</label>
						{numInput(rotation.z, (v) => setRot("z", v))}
					</div>
				</div>
			</DialogContent>
			<DialogActions>
				<Button variant="cancel" onClick={() => onCancel(getData())} />
				<Button variant="ok" onClick={() => onOk(getData())} />
			</DialogActions>
		</Dialog>
	);
}
