// src/components/controlPanels/csi_template.vue
/* Web Lic - Copyright (C) 2018 Remi Gagne */

<template>
	<div>
		<transform-panel
			:template-entry="templateEntry"
			@new-values="newValues"
		/>
		<fill-panel
			:title="template.csi.displacement_arrow_color"
			template-entry="step.csi.displacementArrow"
			@new-values="newArrowStyle"
		/>
		<!--<border-panel title="Displacement Arrow Border" v-on:new-values="newArrowStyle"></border-panel>-->
	</div>
</template>

<script>

import store from '../../store';
import TransformPanel from './transform.vue';
import FillPanel from './fill.vue';

export default {
	components: {TransformPanel, FillPanel},
	props: ['selectedItem', 'templateEntry'],
	methods: {
		apply() {
			this.$parent.applyDirtyAction('csi');
		},
		newArrowStyle() {
			store.get.csi(this.selectedItem).isDirty = true;
			this.$emit('new-values', 'CSI');
		},
		newValues() {
			store.get.csi(this.selectedItem).isDirty = true;
			this.$emit('new-values', {type: 'CSI', noLayout: true});
		}
	}
};

</script>

// src/components/controlPanels/csi_template.tsx
/* Web Lic - Copyright (C) 2018 Remi Gagne */

import React from "react";

import store from "../../store";
import FillPanel from "./fill";
import TransformPanel from "./transform";

interface CsiTemplatePanelProps {
	selectedItem: any;
	templateEntry: string;
	onNewValues: (opts: string | { type: string; noLayout?: boolean }) => void;
}

export default function CsiTemplatePanel({
	selectedItem,
	templateEntry,
	onNewValues,
}: CsiTemplatePanelProps) {
	function newArrowStyle() {
		store.get.csi(selectedItem).isDirty = true;
		onNewValues("csi");
	}

	function newValues() {
		store.get.csi(selectedItem).isDirty = true;
		onNewValues({ type: "csi", noLayout: true });
	}

	return (
		<div>
			<TransformPanel templateEntry={templateEntry} onNewValues={newValues} />
			<FillPanel
				title="template.csi.displacement_arrow_color"
				templateEntry="step.csi.displacementArrow"
				onNewValues={newArrowStyle}
			/>
		</div>
	);
}
