// src/components/controlPanels/fill_border.vue
/* Web Lic - Copyright (C) 2018 Remi Gagne */

<template>
	<div>
		<fill-panel
			:template-entry="templateEntry"
			@new-values="newValues"
		/>
		<border-panel
			:template-entry="templateEntry"
			@new-values="newValues"
		/>
	</div>
</template>

<script setup lang="ts">

import FillPanel from './fill.vue';
import BorderPanel from './border.vue';

const props = defineProps<{templateEntry: string}>();
const emit = defineEmits(['new-values']);

function newValues() {
	emit('new-values', props.templateEntry);
}

</script>

// src/components/controlPanels/fill_border.tsx
/* Web Lic - Copyright (C) 2018 Remi Gagne */

import React from "react";

import BorderPanel from "./border";
import FillPanel from "./fill";

interface Props {
	templateEntry: string;
	onNewValues: (opts: any) => void;
}

export default function FillBorderPanel({ templateEntry, onNewValues }: Props) {
	return (
		<div>
			<FillPanel templateEntry={templateEntry} onNewValues={onNewValues} />
			<BorderPanel templateEntry={templateEntry} onNewValues={onNewValues} />
		</div>
	);
}
