// src/components/controlPanels/font.vue
/* Web Lic - Copyright (C) 2018 Remi Gagne */

<template>
	<panel-base title="glossary.font" label-width="70px">
		<el-form-item label-width="0px">
			<el-select
				v-model="family"
				@visible-change="cacheFontName"
				@change="updateFontName"
			>
				<el-option-group v-for="group in familyNames" :key="group.label">
					<el-option
						v-for="font in group.options"
						:key="font"
						:value="font"
					>
						{{font}}
					</el-option>
				</el-option-group>
			</el-select>
		</el-form-item>
		<el-form-item label-width="0px">
			<el-checkbox-button
				v-model="bold"
				class="fontStyleButton"
				@change="updateValues()"
			>
				<strong>{{tr('template.font.bold_character')}}</strong>
			</el-checkbox-button>
			<el-checkbox-button
				v-model="italic"
				class="fontStyleButton"
				@change="updateValues()"
			>
				<em>{{tr('template.font.italic_character')}}</em>
			</el-checkbox-button>
			<!-- <el-checkbox-button
				v-model="underline"
				class="fontStyleButton"
				@change="updateValues()"
			>
				<u>{{tr('template.font.underline_character')}}</u>
			</el-checkbox-button> -->
		</el-form-item>
		<el-form-item :label="tr('glossary.size')">
			<input
				v-model.number="size"
				type="number"
				min="0"
				class="form-control"
				@input="updateValues"
			>
		</el-form-item>
		<el-form-item :label="tr('glossary.color')">
			<el-color-picker
				v-model="color"
				show-alpha
				@active-change="updateColor"
				@change="updateValues"
			/>
		</el-form-item>
	</panel-base>
</template>

<script>

import _ from '../../util';
import store from '../../store';
import DialogManager from '../../dialog';
import fontNameDialog from '../../dialogs/font_name.vue';
import PanelBase from './panel_base.vue';

const getFamilyNames = fontNameDialog.methods.getFamilyNames;
const addCustomFont = fontNameDialog.methods.addCustomFont;

// TODO: support underlining fonts in general
export default {
	components: {PanelBase},
	props: ['templateEntry'],
	data() {
		const template = _.get(store.state.template, this.templateEntry);
		const fontParts = _.fontToFontParts(template.font);
		addCustomFont(fontParts.fontFamily);
		return {
			family: fontParts.fontFamily,
			size: parseInt(fontParts.fontSize, 10),
			bold: fontParts.fontWeight === 'bold',
			italic: fontParts.fontStyle === 'italic',
			underline: false,
			color: template.color,
			familyNames: getFamilyNames(),
		};
	},
	methods: {
		cacheFontName(show) {
			if (show) {
				this._lastFontFamily = this.family;
			}
		},
		updateFontName() {
			if (this.family === 'Custom...') {
				DialogManager(fontNameDialog, dialog => {
					dialog.$on('ok', fontName => {
						this.family = fontName;
						this.familyNames = getFamilyNames();
						this.updateValues();
					});
					dialog.$on('cancel', () => {
						this.family = this._lastFontFamily;
					});
					dialog.font = _.fontString(this);
					dialog.fontName = '';
				});
			} else {
				this.updateValues();
			}
		},
		updateColor(newColor) {
			this.color = (newColor === 'transparent') ? null : newColor;
			this.updateValues();
		},
		updateValues() {
			const template = _.get(store.state.template, this.templateEntry);
			template.font = _.fontString(this);
			template.color = this.color;
			this.$emit('new-values', this.templateEntry);
		},
	},
};

</script>

// src/components/controlPanels/font.tsx
/* Web Lic - Copyright (C) 2018 Remi Gagne */

import React, { useRef, useState } from "react";
import MenuItem from "@mui/material/MenuItem";
import Select, { type SelectChangeEvent } from "@mui/material/Select";

import DialogManager from "../../dialog";
import { addCustomFont, getFamilyNames } from "../../dialogs/font_utils";
import store from "../../store";
import { tr } from "../../translations";
import _ from "../../util";
import { Button } from "../button";
import PanelBase from "./panel_base";

interface FontPanelProps {
	templateEntry: string;
	onNewValues: (opts: any) => void;
}

export default function FontPanel({
	templateEntry,
	onNewValues,
}: FontPanelProps) {
	const template = _.get(store.state.template, templateEntry);
	const initialFontParts = _.fontToFontParts(template.font);
	addCustomFont(initialFontParts.fontFamily || "");

	const [family, setFamily] = useState(initialFontParts.fontFamily || "");
	const [size, setSize] = useState(
		parseInt(initialFontParts.fontSize || "14px", 10)
	);
	const [bold, setBold] = useState(initialFontParts.fontWeight === "bold");
	const [italic, setItalic] = useState(initialFontParts.fontStyle === "italic");
	const [color, setColor] = useState(template.color || "");
	const [familyNames, setFamilyNames] = useState(getFamilyNames);
	const lastFontFamilyRef = useRef(family);

	function updateValues(
		overrides?: Partial<{
			family: string;
			size: number;
			bold: boolean;
			italic: boolean;
			color: string;
		}>
	) {
		const f = overrides?.family ?? family;
		const s = overrides?.size ?? size;
		const b = overrides?.bold ?? bold;
		const i = overrides?.italic ?? italic;
		const c = overrides?.color ?? color;
		const t = _.get(store.state.template, templateEntry);
		t.font = _.fontString({
			family: f,
			size: s,
			bold: b ? "bold" : "",
			italic: i ? "italic" : "",
		});
		t.color = c;
		onNewValues(templateEntry);
	}

	function updateColor(newColor: string) {
		const c = newColor === "transparent" ? null : newColor;
		setColor(c || "");
		updateValues({ color: c || "" });
	}

	function handleFamilyOpen() {
		lastFontFamilyRef.current = family;
	}

	function handleFamilyChange(newFamily: string) {
		if (newFamily === "Custom...") {
			DialogManager("fontNameDialog", (dialog) => {
				dialog.$on("ok", (fontName: string) => {
					setFamily(fontName);
					setFamilyNames(getFamilyNames());
					updateValues({ family: fontName });
				});
				dialog.$on("cancel", () => {
					setFamily(lastFontFamilyRef.current);
				});
				dialog.font = _.fontString({
					family,
					size,
					bold: bold ? "bold" : "",
					italic: italic ? "italic" : "",
				});
				dialog.fontName = "";
			});
		} else {
			setFamily(newFamily);
			updateValues({ family: newFamily });
		}
	}

	return (
		<PanelBase title="glossary.font" labelWidth="70px">
			<div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
				<div>
					<Select
						value={family}
						className="form-dropdown"
						onOpen={handleFamilyOpen}
						onChange={(e: SelectChangeEvent) =>
							handleFamilyChange(e.target.value)
						}
					>
						{familyNames.map((group) =>
							group.options.map((f) => (
								<MenuItem key={f} value={f}>
									{f}
								</MenuItem>
							))
						)}
					</Select>
				</div>
				<div style={{ display: "flex", gap: 4 }}>
					<Button
						variant={bold ? null : "outlined"}
						onClick={() => {
							const b = !bold;
							setBold(b);
							updateValues({ bold: b });
						}}
					>
						<strong>{tr("template.font.bold_character")}</strong>
					</Button>
					<Button
						variant={italic ? null : "outlined"}
						onClick={() => {
							const i = !italic;
							setItalic(i);
							updateValues({ italic: i });
						}}
					>
						<em>{tr("template.font.italic_character")}</em>
					</Button>
				</div>
				<div className="form-row">
					<label>{tr("glossary.size")}</label>
					<input
						type="number"
						min={0}
						className="form-control"
						value={size}
						style={{ width: 80 }}
						onChange={(e) => {
							const s = parseInt(e.target.value, 10);
							setSize(s);
							updateValues({ size: s });
						}}
					/>
				</div>
				<div className="form-row">
					<label>{tr("glossary.color")}</label>
					<input
						type="color"
						value={color || "#000000"}
						onChange={(e) => updateColor(e.target.value)}
						className="form-control color-picker-button"
						style={{ marginRight: 20 }}
					/>
				</div>
			</div>
		</PanelBase>
	);
}
