// src/components/controlPanels/panel_base.tsx
/* Web Lic - Copyright (C) 2018 Remi Gagne */

import React from "react";

import { tr } from "../../translations";

interface PanelBaseProps {
	title: string;
	labelWidth?: string;
	children?: React.ReactNode;
}

export default function PanelBase({ title, children }: PanelBaseProps) {
	return (
		<div className="panel-template">
			<h5>{tr(title)}</h5>
			<div className="panel-body">{children}</div>
		</div>
	);
}

// src/components/controlPanels/panel_base.vue
/* Web Lic - Copyright (C) 2018 Remi Gagne */

<template>
	<div class="panel-template">
		<h5>{{tr(title)}}</h5>
		<div class="panel-body">
			<el-form :label-width="labelWidth" label-position="left">
				<slot />
			</el-form>
		</div>
	</div>
</template>

<script>

export default {
	props: ['title', 'labelWidth']
};

</script>
