// src/components/controlPanels/pli_template.vue
/* Web Lic - Copyright (C) 2018 Remi Gagne */

<template>
	<div>
		<panel-base title="template.pli.content">
			<div class="panel-row">
				<label class="lic-checkbox">
					<input
						v-model="includeSubmodels"
						type="checkbox"
						@change="updateValues"
					>
					{{t('template.pli.include_submodels')}}
				</label>
			</div>
		</panel-base>
		<fill-panel
			template-entry="pli"
			@new-values="newValues"
		/>
		<border-panel
			template-entry="pli"
			@new-values="newValues"
		/>
	</div>
</template>

<script setup lang="ts">

import {ref} from 'vue';
import {t} from '@/translations';
import store from '../../store';
import PanelBase from './panel_base.vue';
import FillPanel from './fill.vue';
import BorderPanel from './border.vue';

const emit = defineEmits(['new-values']);

const includeSubmodels = ref(store.state.template.pli.includeSubmodels);

function newValues() {
	emit('new-values', 'pli');
}

function updateValues() {
	const template = store.state.template.pli;
	if (includeSubmodels.value !== template.includeSubmodels) {
		template.includeSubmodels = includeSubmodels.value;
		emit('new-values', 'pli');
	}
}

</script>

// src/components/controlPanels/pli_template.tsx
/* Web Lic - Copyright (C) 2018 Remi Gagne */

import React, { useState } from "react";
import Checkbox from "@mui/material/Checkbox";
import FormControlLabel from "@mui/material/FormControlLabel";

import store from "../../store";
import { tr } from "../../translations";
import BorderPanel from "./border";
import FillPanel from "./fill";
import PanelBase from "./panel_base";

interface PliTemplatePanelProps {
	onNewValues: (type: string) => void;
}

export default function PliTemplatePanel({
	onNewValues,
}: PliTemplatePanelProps) {
	const [includeSubmodels, setIncludeSubmodels] = useState(
		() => store.state.template.pli.includeSubmodels
	);

	function updateValues(checked: boolean) {
		const template = store.state.template.pli;
		if (checked !== template.includeSubmodels) {
			template.includeSubmodels = checked;
			setIncludeSubmodels(checked);
			onNewValues("pli");
		}
	}

	return (
		<div>
			<PanelBase title="template.pli.content" labelWidth="100px">
				<FormControlLabel
					className="el-checkbox"
					control={
						<Checkbox
							checked={includeSubmodels}
							onChange={(e) => updateValues(e.target.checked)}
						/>
					}
					label={tr("template.pli.include_submodels")}
				/>
			</PanelBase>
			<FillPanel templateEntry="pli" onNewValues={() => onNewValues("pli")} />
			<BorderPanel templateEntry="pli" onNewValues={() => onNewValues("pli")} />
		</div>
	);
}
