// src/components/controlPanels/pli_item_template.vue
/* Web Lic - Copyright (C) 2018 Remi Gagne */

<script>

import store from '../../store';
import transformPanel from './transform.vue';

export default {
	props: ['selectedItem', 'app'],
	render(createElement) {
		return createElement(
			transformPanel,
			{
				props: {templateEntry: 'pliItem'},
				on: {'new-values': this.newValues},
			},
		);
	},
	methods: {
		apply() {
			this.$parent.applyDirtyAction('pliItem');
		},
		newValues() {
			const pli = store.get.parent(this.selectedItem);
			pli.pliItems.forEach(id => (store.get.pliItem(id).isDirty = true));
			this.$emit('new-values', 'pliitem');
		},
	},
};

</script>

// src/components/controlPanels/pli_item_template.tsx
/* Web Lic - Copyright (C) 2018 Remi Gagne */

import React from "react";

import store from "../../store";
import TransformPanel from "./transform";

interface PliItemTemplatePanelProps {
	selectedItem: any;
	onNewValues: (type: string) => void;
	onApply?: () => void;
}

export default function PliItemTemplatePanel({
	selectedItem,
	onNewValues,
}: PliItemTemplatePanelProps) {
	function newValues() {
		const pli = store.get.parent(selectedItem);
		if (pli) {
			(pli as any).pliItems.forEach(
				(id: number) => (store.get.pliItem(id).isDirty = true)
			);
		}
		onNewValues("pliitem");
	}

	return <TransformPanel templateEntry="pliItem" onNewValues={newValues} />;
}
