// src/components/translate.vue
/* Web Lic - Copyright (C) 2019 Remi Gagne */

<template>
	<licDialog
		id="locale_chooser_dialog"
		:title="tr('dialog.locale_chooser.title')"
		:modal="true"
		:show-close="false"
		:visible="visible"
		width="400px"
	>
		<el-select id="localeChooserSelect" v-model="chosenLocaleCode" @change="changeLanguage">
			<el-option
				v-for="item in languageList"
				:id="`locale_${item.code}`"
				:key="item.code"
				:label="item.language"
				:value="item.code"
			/>
		</el-select>
		<span slot="footer" class="dialog-footer">
			<el-button type="primary" @click="ok()">{{tr('dialog.ok')}}</el-button>
		</span>
	</licDialog>
</template>

<script>

import DialogManager from '../dialog';
import EventBus from '../event_bus';
import * as translate from '../translations';

async function pickLanguage() {
	const currentLocale = translate.getLocale();
	if (currentLocale != null || translate.LanguageList.length < 2) {
		if (currentLocale != null) {
			EventBus.$emit('redraw-ui');
		}
	} else {
		await DialogManager('localeChooserDialog', dialog => {
			dialog.visible = true;
		});
	}
}

export default {
	data() {
		return {
			visible: false,
			chosenLocaleCode: 'en',
			languageList: translate.LanguageList,
		};
	},
	methods: {
		ok() {
			this.visible = false;
			translate.setLocale(this.chosenLocaleCode);
			this.$emit('close');
		},
		changeLanguage() {
			translate.setLocale(this.chosenLocaleCode);
			EventBus.$emit('redraw-ui');
		},
	},
	pickLanguage,
};

</script>

// src/components/translate.tsx
/* Web Lic - Copyright (C) 2019 Remi Gagne */

import React, { useState } from "react";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogTitle from "@mui/material/DialogTitle";
import MenuItem from "@mui/material/MenuItem";
import Select, { type SelectChangeEvent } from "@mui/material/Select";

import EventBus from "../event_bus";
import * as translate from "../translations";
import { tr } from "../translations";
import { Button } from "./button";

interface TranslateDialogProps {
	onClose: () => void;
}

export function TranslateDialog({ onClose }: TranslateDialogProps) {
	const [chosenLocaleCode, setChosenLocaleCode] = useState("en");

	function changeLanguage(e: SelectChangeEvent) {
		const code = e.target.value;
		setChosenLocaleCode(code);
		translate.setLocale(code);
		EventBus.emit("redraw-ui", undefined);
	}

	function ok() {
		translate.setLocale(chosenLocaleCode);
		onClose();
	}

	return (
		<Dialog open id="locale_chooser_dialog" maxWidth="xs" fullWidth>
			<DialogTitle>{tr("dialog.locale_chooser.title")}</DialogTitle>
			<DialogContent>
				<Select
					id="localeChooserSelect"
					className="form-dropdown"
					value={chosenLocaleCode}
					onChange={changeLanguage}
					fullWidth
				>
					{translate.LanguageList.map((item) => (
						<MenuItem
							key={item.code}
							id={`locale_${item.code}`}
							value={item.code}
						>
							{item.language}
						</MenuItem>
					))}
				</Select>
			</DialogContent>
			<DialogActions>
				<Button variant="ok" onClick={ok} />
			</DialogActions>
		</Dialog>
	);
}

TranslateDialog.needLocale = function () {
	const currentLocale = translate.getLocale();
	if (currentLocale != null || translate.LanguageList.length < 2) {
		return false;
	}
	return true;
};
